[project]
name = "ai-news-bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "mcp>=1.14.0",
    "requests>=2.32.5",
    "webexteamssdk>=1.7",
]
